// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfbvulkeblwndvonziex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmYnZ1bGtlYmx3bmR2b256aWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDIwMjMsImV4cCI6MjA3MDA3ODAyM30.K952s5fkOrpvxyVetfnNh8B5KGJYZ5l7IRiUQeBAzz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});